// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf/asset-properties.proto

package com.hashmapinc.tempus;

public final class CompactionProtos {
  private CompactionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CompactionRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 uri = 1;
    /**
     * <code>required int64 uri = 1;</code>
     */
    boolean hasUri();
    /**
     * <code>required int64 uri = 1;</code>
     */
    long getUri();

    // required int64 startTime = 2;
    /**
     * <code>required int64 startTime = 2;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required int64 startTime = 2;</code>
     */
    long getStartTime();

    // required int64 endTime = 3;
    /**
     * <code>required int64 endTime = 3;</code>
     */
    boolean hasEndTime();
    /**
     * <code>required int64 endTime = 3;</code>
     */
    long getEndTime();

    // required string dataType = 4;
    /**
     * <code>required string dataType = 4;</code>
     */
    boolean hasDataType();
    /**
     * <code>required string dataType = 4;</code>
     */
    java.lang.String getDataType();
    /**
     * <code>required string dataType = 4;</code>
     */
    com.google.protobuf.ByteString
        getDataTypeBytes();
  }
  /**
   * Protobuf type {@code CompactionRequest}
   */
  public static final class CompactionRequest extends
      com.google.protobuf.GeneratedMessage
      implements CompactionRequestOrBuilder {
    // Use CompactionRequest.newBuilder() to construct.
    private CompactionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CompactionRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CompactionRequest defaultInstance;
    public static CompactionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CompactionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CompactionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uri_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTime_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dataType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hashmapinc.tempus.CompactionProtos.CompactionRequest.class, com.hashmapinc.tempus.CompactionProtos.CompactionRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CompactionRequest> PARSER =
        new com.google.protobuf.AbstractParser<CompactionRequest>() {
      public CompactionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompactionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CompactionRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private long uri_;
    /**
     * <code>required int64 uri = 1;</code>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uri = 1;</code>
     */
    public long getUri() {
      return uri_;
    }

    // required int64 startTime = 2;
    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <code>required int64 startTime = 2;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 startTime = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    // required int64 endTime = 3;
    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>required int64 endTime = 3;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 endTime = 3;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    // required string dataType = 4;
    public static final int DATATYPE_FIELD_NUMBER = 4;
    private java.lang.Object dataType_;
    /**
     * <code>required string dataType = 4;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string dataType = 4;</code>
     */
    public java.lang.String getDataType() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dataType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uri_ = 0L;
      startTime_ = 0L;
      endTime_ = 0L;
      dataType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uri_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDataTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uri_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDataTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hashmapinc.tempus.CompactionProtos.CompactionRequest)) {
        return super.equals(obj);
      }
      com.hashmapinc.tempus.CompactionProtos.CompactionRequest other = (com.hashmapinc.tempus.CompactionProtos.CompactionRequest) obj;

      boolean result = true;
      result = result && (hasUri() == other.hasUri());
      if (hasUri()) {
        result = result && (getUri()
            == other.getUri());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && (getEndTime()
            == other.getEndTime());
      }
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && getDataType()
            .equals(other.getDataType());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUri()) {
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getUri());
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStartTime());
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getEndTime());
      }
      if (hasDataType()) {
        hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDataType().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hashmapinc.tempus.CompactionProtos.CompactionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CompactionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hashmapinc.tempus.CompactionProtos.CompactionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hashmapinc.tempus.CompactionProtos.CompactionRequest.class, com.hashmapinc.tempus.CompactionProtos.CompactionRequest.Builder.class);
      }

      // Construct using com.hashmapinc.tempus.CompactionProtos.CompactionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uri_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        dataType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionRequest_descriptor;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionRequest getDefaultInstanceForType() {
        return com.hashmapinc.tempus.CompactionProtos.CompactionRequest.getDefaultInstance();
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionRequest build() {
        com.hashmapinc.tempus.CompactionProtos.CompactionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionRequest buildPartial() {
        com.hashmapinc.tempus.CompactionProtos.CompactionRequest result = new com.hashmapinc.tempus.CompactionProtos.CompactionRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataType_ = dataType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hashmapinc.tempus.CompactionProtos.CompactionRequest) {
          return mergeFrom((com.hashmapinc.tempus.CompactionProtos.CompactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hashmapinc.tempus.CompactionProtos.CompactionRequest other) {
        if (other == com.hashmapinc.tempus.CompactionProtos.CompactionRequest.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasDataType()) {
          bitField0_ |= 0x00000008;
          dataType_ = other.dataType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        if (!hasDataType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hashmapinc.tempus.CompactionProtos.CompactionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hashmapinc.tempus.CompactionProtos.CompactionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 uri = 1;
      private long uri_ ;
      /**
       * <code>required int64 uri = 1;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public long getUri() {
        return uri_;
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public Builder setUri(long value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = 0L;
        onChanged();
        return this;
      }

      // required int64 startTime = 2;
      private long startTime_ ;
      /**
       * <code>required int64 startTime = 2;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 startTime = 2;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required int64 startTime = 2;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000002;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 startTime = 2;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 endTime = 3;
      private long endTime_ ;
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 endTime = 3;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // required string dataType = 4;
      private java.lang.Object dataType_ = "";
      /**
       * <code>required string dataType = 4;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string dataType = 4;</code>
       */
      public java.lang.String getDataType() {
        java.lang.Object ref = dataType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dataType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dataType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        java.lang.Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dataType = 4;</code>
       */
      public Builder setDataType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dataType = 4;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataType_ = getDefaultInstance().getDataType();
        onChanged();
        return this;
      }
      /**
       * <code>required string dataType = 4;</code>
       */
      public Builder setDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CompactionRequest)
    }

    static {
      defaultInstance = new CompactionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CompactionRequest)
  }

  public interface CompactedDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 uri = 1;
    /**
     * <code>required int64 uri = 1;</code>
     */
    boolean hasUri();
    /**
     * <code>required int64 uri = 1;</code>
     */
    long getUri();

    // required bytes ts = 2;
    /**
     * <code>required bytes ts = 2;</code>
     */
    boolean hasTs();
    /**
     * <code>required bytes ts = 2;</code>
     */
    com.google.protobuf.ByteString getTs();

    // required bytes quality = 3;
    /**
     * <code>required bytes quality = 3;</code>
     */
    boolean hasQuality();
    /**
     * <code>required bytes quality = 3;</code>
     */
    com.google.protobuf.ByteString getQuality();

    // required bytes vb = 5;
    /**
     * <code>required bytes vb = 5;</code>
     */
    boolean hasVb();
    /**
     * <code>required bytes vb = 5;</code>
     */
    com.google.protobuf.ByteString getVb();

    // optional int32 numSamples = 6;
    /**
     * <code>optional int32 numSamples = 6;</code>
     */
    boolean hasNumSamples();
    /**
     * <code>optional int32 numSamples = 6;</code>
     */
    int getNumSamples();

    // required int64 firstptTs = 7;
    /**
     * <code>required int64 firstptTs = 7;</code>
     */
    boolean hasFirstptTs();
    /**
     * <code>required int64 firstptTs = 7;</code>
     */
    long getFirstptTs();
  }
  /**
   * Protobuf type {@code CompactedData}
   */
  public static final class CompactedData extends
      com.google.protobuf.GeneratedMessage
      implements CompactedDataOrBuilder {
    // Use CompactedData.newBuilder() to construct.
    private CompactedData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CompactedData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CompactedData defaultInstance;
    public static CompactedData getDefaultInstance() {
      return defaultInstance;
    }

    public CompactedData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CompactedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uri_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ts_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              quality_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              vb_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              numSamples_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              firstptTs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactedData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hashmapinc.tempus.CompactionProtos.CompactedData.class, com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder.class);
    }

    public static com.google.protobuf.Parser<CompactedData> PARSER =
        new com.google.protobuf.AbstractParser<CompactedData>() {
      public CompactedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompactedData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CompactedData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 uri = 1;
    public static final int URI_FIELD_NUMBER = 1;
    private long uri_;
    /**
     * <code>required int64 uri = 1;</code>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uri = 1;</code>
     */
    public long getUri() {
      return uri_;
    }

    // required bytes ts = 2;
    public static final int TS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString ts_;
    /**
     * <code>required bytes ts = 2;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes ts = 2;</code>
     */
    public com.google.protobuf.ByteString getTs() {
      return ts_;
    }

    // required bytes quality = 3;
    public static final int QUALITY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString quality_;
    /**
     * <code>required bytes quality = 3;</code>
     */
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes quality = 3;</code>
     */
    public com.google.protobuf.ByteString getQuality() {
      return quality_;
    }

    // required bytes vb = 5;
    public static final int VB_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString vb_;
    /**
     * <code>required bytes vb = 5;</code>
     */
    public boolean hasVb() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes vb = 5;</code>
     */
    public com.google.protobuf.ByteString getVb() {
      return vb_;
    }

    // optional int32 numSamples = 6;
    public static final int NUMSAMPLES_FIELD_NUMBER = 6;
    private int numSamples_;
    /**
     * <code>optional int32 numSamples = 6;</code>
     */
    public boolean hasNumSamples() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 numSamples = 6;</code>
     */
    public int getNumSamples() {
      return numSamples_;
    }

    // required int64 firstptTs = 7;
    public static final int FIRSTPTTS_FIELD_NUMBER = 7;
    private long firstptTs_;
    /**
     * <code>required int64 firstptTs = 7;</code>
     */
    public boolean hasFirstptTs() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 firstptTs = 7;</code>
     */
    public long getFirstptTs() {
      return firstptTs_;
    }

    private void initFields() {
      uri_ = 0L;
      ts_ = com.google.protobuf.ByteString.EMPTY;
      quality_ = com.google.protobuf.ByteString.EMPTY;
      vb_ = com.google.protobuf.ByteString.EMPTY;
      numSamples_ = 0;
      firstptTs_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuality()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstptTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uri_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, quality_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, vb_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, numSamples_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(7, firstptTs_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uri_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, quality_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, vb_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, numSamples_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, firstptTs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hashmapinc.tempus.CompactionProtos.CompactedData)) {
        return super.equals(obj);
      }
      com.hashmapinc.tempus.CompactionProtos.CompactedData other = (com.hashmapinc.tempus.CompactionProtos.CompactedData) obj;

      boolean result = true;
      result = result && (hasUri() == other.hasUri());
      if (hasUri()) {
        result = result && (getUri()
            == other.getUri());
      }
      result = result && (hasTs() == other.hasTs());
      if (hasTs()) {
        result = result && getTs()
            .equals(other.getTs());
      }
      result = result && (hasQuality() == other.hasQuality());
      if (hasQuality()) {
        result = result && getQuality()
            .equals(other.getQuality());
      }
      result = result && (hasVb() == other.hasVb());
      if (hasVb()) {
        result = result && getVb()
            .equals(other.getVb());
      }
      result = result && (hasNumSamples() == other.hasNumSamples());
      if (hasNumSamples()) {
        result = result && (getNumSamples()
            == other.getNumSamples());
      }
      result = result && (hasFirstptTs() == other.hasFirstptTs());
      if (hasFirstptTs()) {
        result = result && (getFirstptTs()
            == other.getFirstptTs());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUri()) {
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getUri());
      }
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + getTs().hashCode();
      }
      if (hasQuality()) {
        hash = (37 * hash) + QUALITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuality().hashCode();
      }
      if (hasVb()) {
        hash = (37 * hash) + VB_FIELD_NUMBER;
        hash = (53 * hash) + getVb().hashCode();
      }
      if (hasNumSamples()) {
        hash = (37 * hash) + NUMSAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getNumSamples();
      }
      if (hasFirstptTs()) {
        hash = (37 * hash) + FIRSTPTTS_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getFirstptTs());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hashmapinc.tempus.CompactionProtos.CompactedData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CompactedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactedData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hashmapinc.tempus.CompactionProtos.CompactedData.class, com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder.class);
      }

      // Construct using com.hashmapinc.tempus.CompactionProtos.CompactedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uri_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        quality_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        vb_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        numSamples_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        firstptTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactedData_descriptor;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactedData getDefaultInstanceForType() {
        return com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance();
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactedData build() {
        com.hashmapinc.tempus.CompactionProtos.CompactedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactedData buildPartial() {
        com.hashmapinc.tempus.CompactionProtos.CompactedData result = new com.hashmapinc.tempus.CompactionProtos.CompactedData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quality_ = quality_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.vb_ = vb_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numSamples_ = numSamples_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.firstptTs_ = firstptTs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hashmapinc.tempus.CompactionProtos.CompactedData) {
          return mergeFrom((com.hashmapinc.tempus.CompactionProtos.CompactedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hashmapinc.tempus.CompactionProtos.CompactedData other) {
        if (other == com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance()) return this;
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        if (other.hasVb()) {
          setVb(other.getVb());
        }
        if (other.hasNumSamples()) {
          setNumSamples(other.getNumSamples());
        }
        if (other.hasFirstptTs()) {
          setFirstptTs(other.getFirstptTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUri()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        if (!hasQuality()) {
          
          return false;
        }
        if (!hasVb()) {
          
          return false;
        }
        if (!hasFirstptTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hashmapinc.tempus.CompactionProtos.CompactedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hashmapinc.tempus.CompactionProtos.CompactedData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 uri = 1;
      private long uri_ ;
      /**
       * <code>required int64 uri = 1;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public long getUri() {
        return uri_;
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public Builder setUri(long value) {
        bitField0_ |= 0x00000001;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uri = 1;</code>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = 0L;
        onChanged();
        return this;
      }

      // required bytes ts = 2;
      private com.google.protobuf.ByteString ts_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes ts = 2;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes ts = 2;</code>
       */
      public com.google.protobuf.ByteString getTs() {
        return ts_;
      }
      /**
       * <code>required bytes ts = 2;</code>
       */
      public Builder setTs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes ts = 2;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = getDefaultInstance().getTs();
        onChanged();
        return this;
      }

      // required bytes quality = 3;
      private com.google.protobuf.ByteString quality_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes quality = 3;</code>
       */
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes quality = 3;</code>
       */
      public com.google.protobuf.ByteString getQuality() {
        return quality_;
      }
      /**
       * <code>required bytes quality = 3;</code>
       */
      public Builder setQuality(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes quality = 3;</code>
       */
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quality_ = getDefaultInstance().getQuality();
        onChanged();
        return this;
      }

      // required bytes vb = 5;
      private com.google.protobuf.ByteString vb_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes vb = 5;</code>
       */
      public boolean hasVb() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes vb = 5;</code>
       */
      public com.google.protobuf.ByteString getVb() {
        return vb_;
      }
      /**
       * <code>required bytes vb = 5;</code>
       */
      public Builder setVb(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        vb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes vb = 5;</code>
       */
      public Builder clearVb() {
        bitField0_ = (bitField0_ & ~0x00000008);
        vb_ = getDefaultInstance().getVb();
        onChanged();
        return this;
      }

      // optional int32 numSamples = 6;
      private int numSamples_ ;
      /**
       * <code>optional int32 numSamples = 6;</code>
       */
      public boolean hasNumSamples() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 numSamples = 6;</code>
       */
      public int getNumSamples() {
        return numSamples_;
      }
      /**
       * <code>optional int32 numSamples = 6;</code>
       */
      public Builder setNumSamples(int value) {
        bitField0_ |= 0x00000010;
        numSamples_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numSamples = 6;</code>
       */
      public Builder clearNumSamples() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numSamples_ = 0;
        onChanged();
        return this;
      }

      // required int64 firstptTs = 7;
      private long firstptTs_ ;
      /**
       * <code>required int64 firstptTs = 7;</code>
       */
      public boolean hasFirstptTs() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 firstptTs = 7;</code>
       */
      public long getFirstptTs() {
        return firstptTs_;
      }
      /**
       * <code>required int64 firstptTs = 7;</code>
       */
      public Builder setFirstptTs(long value) {
        bitField0_ |= 0x00000020;
        firstptTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 firstptTs = 7;</code>
       */
      public Builder clearFirstptTs() {
        bitField0_ = (bitField0_ & ~0x00000020);
        firstptTs_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CompactedData)
    }

    static {
      defaultInstance = new CompactedData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CompactedData)
  }

  public interface CompactionResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .CompactedData packedData = 1;
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    boolean hasPackedData();
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    com.hashmapinc.tempus.CompactionProtos.CompactedData getPackedData();
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder getPackedDataOrBuilder();

    // required bool isFail = 2 [default = false];
    /**
     * <code>required bool isFail = 2 [default = false];</code>
     */
    boolean hasIsFail();
    /**
     * <code>required bool isFail = 2 [default = false];</code>
     */
    boolean getIsFail();

    // optional string errMsg = 3 [default = "NO_ERR"];
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    boolean hasErrMsg();
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code CompactionResponse}
   */
  public static final class CompactionResponse extends
      com.google.protobuf.GeneratedMessage
      implements CompactionResponseOrBuilder {
    // Use CompactionResponse.newBuilder() to construct.
    private CompactionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CompactionResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CompactionResponse defaultInstance;
    public static CompactionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CompactionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CompactionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = packedData_.toBuilder();
              }
              packedData_ = input.readMessage(com.hashmapinc.tempus.CompactionProtos.CompactedData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(packedData_);
                packedData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isFail_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hashmapinc.tempus.CompactionProtos.CompactionResponse.class, com.hashmapinc.tempus.CompactionProtos.CompactionResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CompactionResponse> PARSER =
        new com.google.protobuf.AbstractParser<CompactionResponse>() {
      public CompactionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompactionResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CompactionResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .CompactedData packedData = 1;
    public static final int PACKEDDATA_FIELD_NUMBER = 1;
    private com.hashmapinc.tempus.CompactionProtos.CompactedData packedData_;
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    public boolean hasPackedData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    public com.hashmapinc.tempus.CompactionProtos.CompactedData getPackedData() {
      return packedData_;
    }
    /**
     * <code>optional .CompactedData packedData = 1;</code>
     */
    public com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder getPackedDataOrBuilder() {
      return packedData_;
    }

    // required bool isFail = 2 [default = false];
    public static final int ISFAIL_FIELD_NUMBER = 2;
    private boolean isFail_;
    /**
     * <code>required bool isFail = 2 [default = false];</code>
     */
    public boolean hasIsFail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isFail = 2 [default = false];</code>
     */
    public boolean getIsFail() {
      return isFail_;
    }

    // optional string errMsg = 3 [default = "NO_ERR"];
    public static final int ERRMSG_FIELD_NUMBER = 3;
    private java.lang.Object errMsg_;
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      packedData_ = com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance();
      isFail_ = false;
      errMsg_ = "NO_ERR";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsFail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPackedData()) {
        if (!getPackedData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, packedData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isFail_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packedData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isFail_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hashmapinc.tempus.CompactionProtos.CompactionResponse)) {
        return super.equals(obj);
      }
      com.hashmapinc.tempus.CompactionProtos.CompactionResponse other = (com.hashmapinc.tempus.CompactionProtos.CompactionResponse) obj;

      boolean result = true;
      result = result && (hasPackedData() == other.hasPackedData());
      if (hasPackedData()) {
        result = result && getPackedData()
            .equals(other.getPackedData());
      }
      result = result && (hasIsFail() == other.hasIsFail());
      if (hasIsFail()) {
        result = result && (getIsFail()
            == other.getIsFail());
      }
      result = result && (hasErrMsg() == other.hasErrMsg());
      if (hasErrMsg()) {
        result = result && getErrMsg()
            .equals(other.getErrMsg());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPackedData()) {
        hash = (37 * hash) + PACKEDDATA_FIELD_NUMBER;
        hash = (53 * hash) + getPackedData().hashCode();
      }
      if (hasIsFail()) {
        hash = (37 * hash) + ISFAIL_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getIsFail());
      }
      if (hasErrMsg()) {
        hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hashmapinc.tempus.CompactionProtos.CompactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hashmapinc.tempus.CompactionProtos.CompactionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CompactionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hashmapinc.tempus.CompactionProtos.CompactionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hashmapinc.tempus.CompactionProtos.CompactionResponse.class, com.hashmapinc.tempus.CompactionProtos.CompactionResponse.Builder.class);
      }

      // Construct using com.hashmapinc.tempus.CompactionProtos.CompactionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPackedDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (packedDataBuilder_ == null) {
          packedData_ = com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance();
        } else {
          packedDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        isFail_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = "NO_ERR";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hashmapinc.tempus.CompactionProtos.internal_static_CompactionResponse_descriptor;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionResponse getDefaultInstanceForType() {
        return com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance();
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionResponse build() {
        com.hashmapinc.tempus.CompactionProtos.CompactionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hashmapinc.tempus.CompactionProtos.CompactionResponse buildPartial() {
        com.hashmapinc.tempus.CompactionProtos.CompactionResponse result = new com.hashmapinc.tempus.CompactionProtos.CompactionResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (packedDataBuilder_ == null) {
          result.packedData_ = packedData_;
        } else {
          result.packedData_ = packedDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isFail_ = isFail_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hashmapinc.tempus.CompactionProtos.CompactionResponse) {
          return mergeFrom((com.hashmapinc.tempus.CompactionProtos.CompactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hashmapinc.tempus.CompactionProtos.CompactionResponse other) {
        if (other == com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance()) return this;
        if (other.hasPackedData()) {
          mergePackedData(other.getPackedData());
        }
        if (other.hasIsFail()) {
          setIsFail(other.getIsFail());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000004;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsFail()) {
          
          return false;
        }
        if (hasPackedData()) {
          if (!getPackedData().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hashmapinc.tempus.CompactionProtos.CompactionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hashmapinc.tempus.CompactionProtos.CompactionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .CompactedData packedData = 1;
      private com.hashmapinc.tempus.CompactionProtos.CompactedData packedData_ = com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hashmapinc.tempus.CompactionProtos.CompactedData, com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder, com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder> packedDataBuilder_;
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public boolean hasPackedData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public com.hashmapinc.tempus.CompactionProtos.CompactedData getPackedData() {
        if (packedDataBuilder_ == null) {
          return packedData_;
        } else {
          return packedDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public Builder setPackedData(com.hashmapinc.tempus.CompactionProtos.CompactedData value) {
        if (packedDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packedData_ = value;
          onChanged();
        } else {
          packedDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public Builder setPackedData(
          com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder builderForValue) {
        if (packedDataBuilder_ == null) {
          packedData_ = builderForValue.build();
          onChanged();
        } else {
          packedDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public Builder mergePackedData(com.hashmapinc.tempus.CompactionProtos.CompactedData value) {
        if (packedDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              packedData_ != com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance()) {
            packedData_ =
              com.hashmapinc.tempus.CompactionProtos.CompactedData.newBuilder(packedData_).mergeFrom(value).buildPartial();
          } else {
            packedData_ = value;
          }
          onChanged();
        } else {
          packedDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public Builder clearPackedData() {
        if (packedDataBuilder_ == null) {
          packedData_ = com.hashmapinc.tempus.CompactionProtos.CompactedData.getDefaultInstance();
          onChanged();
        } else {
          packedDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder getPackedDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPackedDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      public com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder getPackedDataOrBuilder() {
        if (packedDataBuilder_ != null) {
          return packedDataBuilder_.getMessageOrBuilder();
        } else {
          return packedData_;
        }
      }
      /**
       * <code>optional .CompactedData packedData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hashmapinc.tempus.CompactionProtos.CompactedData, com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder, com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder>
          getPackedDataFieldBuilder() {
        if (packedDataBuilder_ == null) {
          packedDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hashmapinc.tempus.CompactionProtos.CompactedData, com.hashmapinc.tempus.CompactionProtos.CompactedData.Builder, com.hashmapinc.tempus.CompactionProtos.CompactedDataOrBuilder>(
                  packedData_,
                  getParentForChildren(),
                  isClean());
          packedData_ = null;
        }
        return packedDataBuilder_;
      }

      // required bool isFail = 2 [default = false];
      private boolean isFail_ ;
      /**
       * <code>required bool isFail = 2 [default = false];</code>
       */
      public boolean hasIsFail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isFail = 2 [default = false];</code>
       */
      public boolean getIsFail() {
        return isFail_;
      }
      /**
       * <code>required bool isFail = 2 [default = false];</code>
       */
      public Builder setIsFail(boolean value) {
        bitField0_ |= 0x00000002;
        isFail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isFail = 2 [default = false];</code>
       */
      public Builder clearIsFail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isFail_ = false;
        onChanged();
        return this;
      }

      // optional string errMsg = 3 [default = "NO_ERR"];
      private java.lang.Object errMsg_ = "NO_ERR";
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errMsg = 3 [default = "NO_ERR"];</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CompactionResponse)
    }

    static {
      defaultInstance = new CompactionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CompactionResponse)
  }

  /**
   * Protobuf service {@code CompactionService}
   */
  public static abstract class CompactionService
      implements com.google.protobuf.Service {
    protected CompactionService() {}

    public interface Interface {
      /**
       * <code>rpc compactData(.CompactionRequest) returns (.CompactionResponse);</code>
       */
      public abstract void compactData(
          com.google.protobuf.RpcController controller,
          com.hashmapinc.tempus.CompactionProtos.CompactionRequest request,
          com.google.protobuf.RpcCallback<com.hashmapinc.tempus.CompactionProtos.CompactionResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CompactionService() {
        @java.lang.Override
        public  void compactData(
            com.google.protobuf.RpcController controller,
            com.hashmapinc.tempus.CompactionProtos.CompactionRequest request,
            com.google.protobuf.RpcCallback<com.hashmapinc.tempus.CompactionProtos.CompactionResponse> done) {
          impl.compactData(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.compactData(controller, (com.hashmapinc.tempus.CompactionProtos.CompactionRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hashmapinc.tempus.CompactionProtos.CompactionRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc compactData(.CompactionRequest) returns (.CompactionResponse);</code>
     */
    public abstract void compactData(
        com.google.protobuf.RpcController controller,
        com.hashmapinc.tempus.CompactionProtos.CompactionRequest request,
        com.google.protobuf.RpcCallback<com.hashmapinc.tempus.CompactionProtos.CompactionResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hashmapinc.tempus.CompactionProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.compactData(controller, (com.hashmapinc.tempus.CompactionProtos.CompactionRequest)request,
            com.google.protobuf.RpcUtil.<com.hashmapinc.tempus.CompactionProtos.CompactionResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hashmapinc.tempus.CompactionProtos.CompactionRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hashmapinc.tempus.CompactionProtos.CompactionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void compactData(
          com.google.protobuf.RpcController controller,
          com.hashmapinc.tempus.CompactionProtos.CompactionRequest request,
          com.google.protobuf.RpcCallback<com.hashmapinc.tempus.CompactionProtos.CompactionResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hashmapinc.tempus.CompactionProtos.CompactionResponse.class,
            com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hashmapinc.tempus.CompactionProtos.CompactionResponse compactData(
          com.google.protobuf.RpcController controller,
          com.hashmapinc.tempus.CompactionProtos.CompactionRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hashmapinc.tempus.CompactionProtos.CompactionResponse compactData(
          com.google.protobuf.RpcController controller,
          com.hashmapinc.tempus.CompactionProtos.CompactionRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hashmapinc.tempus.CompactionProtos.CompactionResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hashmapinc.tempus.CompactionProtos.CompactionResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CompactionService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CompactionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CompactionRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CompactedData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CompactedData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CompactionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CompactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037Protobuf/asset-properties.proto\"V\n\021Com" +
      "pactionRequest\022\013\n\003uri\030\001 \002(\003\022\021\n\tstartTime" +
      "\030\002 \002(\003\022\017\n\007endTime\030\003 \002(\003\022\020\n\010dataType\030\004 \002(" +
      "\t\"l\n\rCompactedData\022\013\n\003uri\030\001 \002(\003\022\n\n\002ts\030\002 " +
      "\002(\014\022\017\n\007quality\030\003 \002(\014\022\n\n\002vb\030\005 \002(\014\022\022\n\nnumS" +
      "amples\030\006 \001(\005\022\021\n\tfirstptTs\030\007 \002(\003\"g\n\022Compa" +
      "ctionResponse\022\"\n\npackedData\030\001 \001(\0132\016.Comp" +
      "actedData\022\025\n\006isFail\030\002 \002(\010:\005false\022\026\n\006errM" +
      "sg\030\003 \001(\t:\006NO_ERR2K\n\021CompactionService\0226\n" +
      "\013compactData\022\022.CompactionRequest\032\023.Compa",
      "ctionResponseB=\n!com.hashmapinc.tempus.p" +
      "ersistenceB\020CompactionProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CompactionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CompactionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CompactionRequest_descriptor,
              new java.lang.String[] { "Uri", "StartTime", "EndTime", "DataType", });
          internal_static_CompactedData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CompactedData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CompactedData_descriptor,
              new java.lang.String[] { "Uri", "Ts", "Quality", "Vb", "NumSamples", "FirstptTs", });
          internal_static_CompactionResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CompactionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CompactionResponse_descriptor,
              new java.lang.String[] { "PackedData", "IsFail", "ErrMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
